

# Site Settings
title: 						"Fatih Erdogan"
email: 						"ben@benmurray.us"
description: 				"falan da filan Amigdala da Amigdala"
baseurl: 					""
url: 						"http://ferdogan.net"
logourl: 					"/assets/img/bloglogo.jpg"		
fa-logo: 					"fa-terminal"
paginate: 					5
locale:           			tr_TR


# Author Settings
author_name: 				"Fatih"
author_url: 				"http://ferdogan.net"
author_bio: 				"Ben Murray is a digital advocacy strategist in Washington, D.C."
author_email: 				"ben@benmurray.us"
author_image: 				"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"http://twitter.com/fecassie"
facebook_url: 				"http://facebook.com/fatiherdogananana"
github_url:  				""
youtube_url:  				""
dribbble_url:  				""
googleplus_url: 			"http://plus.google.com/+BenMurrayUS"
instagram_url:  			"http://instagram.com/bnmry"
pinterest_url:  			""
linkedin_url:  				"http://linkedin.com/in/benmurray/"


# Theme Settings
theme_disqus_shortname: 	"fatiherdogan"
theme_google_comments: 		false
theme_analytics_id: 		""
#theme_analytics_domain: 	"ecko.me"
theme_reading_time: 		true
theme_autoload_comments: 	true
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

