# Site wide configuration

title:            Fatih Erdoğan
locale:           en_US
url:              http://fecassie.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Fatih Erdoğan
  avatar: fatih_avatar.jpg
  bio: "Sistem Güvenliği ve Linux meraklısı, özgür yazılımcı, bisiklet tutkunu uykusuz mühendis"
  email: 
  disqus-shortname: fatiherdogan 
  twitter: FeCassie
  facebook: f4tihErd0gan
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: FeCassie
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: fatiherdogan1
  instagram: fat1herdogan
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

author.github: FeCassie
author.stackoverflow: #http://stackoverflow.com/users/123456/username
author.linkedin: fatiherdogan1
author.instagram: fat1herdogan
author.twitter: FeCassie
author.facebook: f4tihErd0gan
